export const ACTIVATE_CONNECTION = 'ACTIVATE_CONNECTION';
export const DEACTIVATE_CONNECTION = 'DEACTIVATE_CONNECTION';

export const SERVER_CONNECTED = 'SERVER_CONNECTED';
export const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED';

export const CREATE_OFFER = 'CREATE_OFFER';

export const UPDATE_PURSES = 'UPDATE_PURSES';
export const UPDATE_OFFERS = 'UPDATE_OFFERS';

export const RESET_STATE = 'RESET_STATE';

export const RECENT_ORDERS = 'RECENT_ORDERS';
