export const ACTIVATE_CONNECTION = 'ACTIVATE_CONNECTION';
export const DEACTIVATE_CONNECTION = 'DEACTIVATE_CONNECTION';

export const SERVER_CONNECTED = 'SERVER_CONNECTED';
export const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED';

export const UPDATE_PURSES = 'UPDATE_PURSES';
export const UPDATE_OFFERS = 'UPDATE_OFFERS';

export const RESET_STATE = 'RESET_STATE';

export const UPDATE_PURSE = 'UPDATE_PURSE';
export const UPDATE_AMOUNT = 'UPDATE_AMOUNT';

export const RECENT_ORDERS = 'RECENT_ORDERS';
